<<<<<<< HEAD
# Colors (Ayu Dark)
=======
# Colors (Monokai Dark)
>>>>>>> 31f3bf0 (feat: add new theme)

# Default colors (darker base)
[colors.primary]
<<<<<<< HEAD
background = '#0A0E14'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'
=======
background = '#0f100d'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black   = '#1b1c18'
red     = '#f92672'
green   = '#a6e22e'
yellow  = '#e6db74'
blue    = '#fd971f'
magenta = '#ae81ff'
cyan    = '#a1efe4'
white   = '#f8f8f2'

# Bright colors
[colors.bright]
black   = '#3c3d35'
red     = '#f92672'
green   = '#a6e22e'
yellow  = '#e6db74'
blue    = '#ffb454'
magenta = '#ae81ff'
cyan    = '#a1efe4'
white   = '#f8f8f0'
>>>>>>> 31f3bf0 (feat: add new theme)
