# Colors (Monokai Dark)

# Default colors (darker base)
[colors.primary]
background = '#0f100d'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black   = '#1b1c18'
red     = '#f92672'
green   = '#a6e22e'
yellow  = '#e6db74'
blue    = '#fd971f'
magenta = '#ae81ff'
cyan    = '#a1efe4'
white   = '#f8f8f2'

# Bright colors
[colors.bright]
black   = '#3c3d35'
red     = '#f92672'
green   = '#a6e22e'
yellow  = '#e6db74'
blue    = '#ffb454'
magenta = '#ae81ff'
cyan    = '#a1efe4'
white   = '#f8f8f0'
