
[window]
padding = { x = 4, y = 2 }
dynamic_padding = false
decorations = "none"
opacity = 0.95
startup_mode = "Windowed"
blur = true

[scrolling]
history = 5000
multiplier = 3

[font]
normal = { family = "SF Mono", style = "Regular" }
bold = { family = "SF Mono", style = "Bold" }
italic = { family = "SF Mono", style = "Italic" }
bold_italic = { family = "SF Mono", style = "Bold Italic" }
size = 11.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = -1 }

[cursor]
style = { shape = "Beam", blinking = "On" }

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Left", mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" }

]

[general]
import = ["~/.config/theme/alacritty.toml"]
